import type { GraphewayConfig } from "../core/index.js";
import { TRAINING_CRAWLERS, SEARCH_CRAWLERS } from "./agents.ts";

/**
 * Build `/robots.txt` with an explicit AI-crawler policy.
 *
 * Default (safe GEO) policy:
 *  - training crawlers blocked  → keeps your content out of model training
 *  - search/retrieval crawlers allowed → keeps you citable in AI answers
 *
 * This mirrors the recommendation that most agent-ready sites adopt.
 */
export function buildRobotsTxt(config: GraphewayConfig): string {
  const allowTraining = config.robots?.allowTraining ?? false;
  const allowSearch = config.robots?.allowSearch ?? true;
  const extraAllow = config.robots?.extraAllow ?? [];
  const extraDisallow = config.robots?.extraDisallow ?? [];

  const lines: string[] = [];
  lines.push("# robots.txt generated by grapheway");
  lines.push("");
  lines.push("User-agent: *");
  lines.push("Allow: /");
  lines.push("");

  // Dedupe by token — GPTBot/ClaudeBot appear in both the training and
  // search lists, so blocking both would otherwise emit duplicate groups.
  const seen = new Set<string>();
  const aiRules: { token: string; kind: string }[] = [
    ...(allowTraining ? [] : TRAINING_CRAWLERS.map((c) => ({ token: c.token, kind: "training" }))),
    ...(allowSearch ? [] : SEARCH_CRAWLERS.map((c) => ({ token: c.token, kind: "search" }))),
    ...extraDisallow.map((t) => ({ token: t, kind: "extra" })),
  ].filter((rule) => (seen.has(rule.token) ? false : (seen.add(rule.token), true)));

  for (const rule of aiRules) {
    lines.push(`# ${rule.kind} crawler`);
    lines.push(`User-agent: ${rule.token}`);
    lines.push("Disallow: /");
    lines.push("");
  }

  for (const token of extraAllow) {
    lines.push(`User-agent: ${token}`);
    lines.push("Allow: /");
    lines.push("");
  }

  lines.push("Sitemap: " + new URL("/sitemap.xml", config.url).href);
  return lines.join("\n") + "\n";
}
